services:
  mysql:
    image: mysql:8.0
    container_name: lch_mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lch-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: lch_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - lch-network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lch_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - lch-network
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lch-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - lch-network
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=http://lch_backend:8000

volumes:
  mysql_data:
  redis_data:

networks:
  lch-network:
    driver: bridge