version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lch_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sw63828
      MYSQL_DATABASE: lch_db
      MYSQL_USER: lch_user
      MYSQL_PASSWORD: sw63828
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: lch_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lch_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: sw63828
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
  redis_data:

networks:
  default:
    name: lch_network